{
 "title": "APC UPS apcupsd",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ups",
    "query": "label_values(apcupsd_apcupsd_last_selftest,model)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cumulative Time On Battery",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_cumulative_time_on_seconds_total"
    }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds/60.0",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Battery Charge Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_charge_percent", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Output Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_ups_load_percent", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_volts", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_line_volts", "legendFormat": "current" },
    { "expr": "apcupsd_line_nominal_volts", "legendFormat": "nominal" }
   ]
  }
 ]
}